### ISSUE TITLE
Add externally hosted library for "Accordion" (Sections With Show/Hide Functionality) widgets

### ISSUE THREAD

**Issue by smillart** [openfed/kiso#12]
**Accordion (Sections With Show/Hide Functionality) widget that implements ARIA Authoring Practices is now available and could be used within Kiso:**

- https://github.com/smillart/WAI-ARIA-Patterns-And-Widgets/tree/master/dist/accordion
- https://smillart.github.io/WAI-ARIA-Patterns-And-Widgets/examples/accordion/

**Drupal info: CDN / Externally hosted library:**

```yaml
aria-accordion:
  remote: https://github.com/smillart/WAI-ARIA-Patterns-And-Widgets
  version: 1.0.1
  license:
    name: MIT
    url: https://github.com/smillart/WAI-ARIA-Patterns-And-Widgets/blob/master/LICENSE
    gpl-compatible: true
  js:
    //smillart.github.io/WAI-ARIA-Patterns-And-Widgets/dist/accordion/js/accordion.min.js: { type: external, minified: true }
```
